### ISSUE TITLE
I can't run TestFiles

### ISSUE THREAD

**Issue by serbier** [SouthGreenPlatform/CulebrONT_pipeline#7]
Hi, I'm interested in using your workflow, now I am doing the test on a local server but I not be able to run the test data you provided named Data-Xoo-sub. This is the command that I used but it stops and prompts an error with canu I post the output of the command: 

culebrONT run_local -t 20 -c ./Test_culebrONT/data_test_config.yaml

    Welcome to CulebrONT version: 2.0.1 ! Created on November 2019
    @author: Julie Orjuela (IRD), Aurore Comte (IRD), Sebastien Ravel (CIRAD), Florian Charriat (INRAE),
    Bao Tram Vi (IRD), François Sabot (IRD) and Sebastien Cunnac (IRD)
    @email: julie.orjuela@ird.fr, aurore.comte@ird.fr

    #     .-+.
    #   `odNNh
    #   +NNd:
    #  .Nh.   ---:`
    #  -Nm`  ````./
    #   oNm/ ```-o-
    #    .yNmo/+/.     .oooooo.               oooo             .o8                  .oooooo.   ooooo      ooo ooooooooooooo
    #    `-+ydNmo.    d8P'  `Y8b              `888            "888                 d8P'  `Y8b  `888b.     `8' 8'   888   `8
    #  `/s+../oNNN:  888          oooo  oooo   888   .ooooo.   888oooo.  oooo d8b 888      888  8 `88b.    8       888
    #  +s/     `hNm  888          `888  `888   888  d88' `88b  d88' `88b `888""8P 888      888  8   `88b.  8       888
    #  os:  ////hNN` 888           888   888   888  888ooo888  888   888  888     888      888  8     `88b.8       888
    #  -so- .//sNNs  `88b    ooo   888   888   888  888    .o  888   888  888     `88b    d88'  8       `888       888
    #   `/oo:.yNd/    `Y8bood8P'   `V88V"V8P' o888o `Y8bod8P'  `Y8bod8P' d888b     `Y8bood8P'  o8o        `8      o888o
    #     -yooo+.
    #   `yNs.`-/oo:
    #   dNo` ....+s+
    #   :shmdddhhy+:

    Please cite our github: https://github.com/SouthGreenPlatform/culebrONT
    Licencied under CeCill-C (http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html)
    and GPLv3 Intellectual property belongs to IRD, CIRAD and authors.
    Documentation avail at: https://culebront-pipeline.readthedocs.io/en/latest/

    ** ENABLE TO GET LAST VERSION, check internet connection
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>

    Config file: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/data_test_config.yaml

    snakemake --latency-wait 1296000 --cores 20 --use-singularity --show-failed-logs --printshellcmds -s /home/scruz/miniconda3/envs/denovoAssembly/lib/python3.7/site-packages/culebrONT/snakefiles/Snakefile --configfile /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/data_test_config.yaml

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 20
Rules claiming more threads will be scaled down.
Job stats:
job                           count    min threads    max threads
--------------------------  -------  -------------  -------------
copy_final_assemblies             6             20             20
final                             1              1              1
preparing_fasta_to_quality        6             20             20
rule_graph                        1             20             20
run_assemblytics                  2             20             20
run_benchmark_time                1             20             20
run_blobtools                     2             20             20
run_busco                         6             20             20
run_busco_stats                   1             20             20
run_busco_version                 1             20             20
run_bwa_mem2                      2             20             20
run_canu                          1             20             20
run_diamond                       2             20             20
run_flagstat                      2             20             20
run_flagstats_stats               1             20             20
run_flye                          1             20             20
run_get_versions                  1             20             20
run_minimap2                      2             20             20
run_mummer                        2             20             20
run_pilon                         2             20             20
run_pilon_first_round             2             20             20
run_quast                         1             20             20
run_racon                         4             20             20
run_racon_version                 1             20             20
run_report                        1             20             20
stats_assembly                    1             20             20
total                            53              1             20

Select jobs to execute...

[Fri Mar 25 15:27:28 2022]
Job 7:
        Launching run_canu
        threads: 20
        input:
            fastq: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/Data-Xoo-sub/fastq/5percentB1-1.fastq.gz
        output:
            fasta: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/assembly.fasta
            trim_forr_fq: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/out_canu.trimmedReads.fasta.gz
        params:
            fasta_canu: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/out_canu.contigs.fasta
            out_dir: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/
            genome_size: 4.8m
            options: useGrid=false
        log:
            output : /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/LOGS/ASSEMBLER/CANU/5percentB1-1_CANU.o
            error: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/LOGS/ASSEMBLER/CANU/5percentB1-1_CANU.e

        [ ! -f /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/CANU-version.txt ] &&  [ ! -d versions ] && mkdir -p versions; canu --version > /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/CANU-version.txt
        ln -s -f /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/CANU-version.txt /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/versions/CANU-version.txt
        (canu useGrid=false -p out_canu -d /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/ genomeSize=4.8m -nanopore  /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/Data-Xoo-sub/fastq/5percentB1-1.fastq.gz;
        ln -s -f /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/out_canu.contigs.fasta /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/assembly.fasta) 1>/bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/LOGS/ASSEMBLER/CANU/5percentB1-1_CANU.o 2>/bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/LOGS/ASSEMBLER/CANU/5percentB1-1_CANU.e

Activating singularity image /home/scruz/miniconda3/envs/denovoAssembly/lib/python3.7/site-packages/culebrONT/containers/Singularity.culebront_tools.sif
INFO:    Converting SIF file to temporary sandbox...
INFO:    Cleaning up image...
[Fri Mar 25 15:29:01 2022]
Error in rule run_canu:
    jobid: 7
    output: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percent                                                                                             B1-1/ASSEMBLERS/CANU/ASSEMBLER/assembly.fasta, /bioinfo1/projects/bean/MinIon/software/Test_                                                                                             culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/out_canu.trimmedReads.fast                                                                                             a.gz, /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/A                                                                                             SSEMBLERS/CANU/ASSEMBLER/CANU-version.txt
    log: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-                                                                                             1/LOGS/ASSEMBLER/CANU/5percentB1-1_CANU.o, /bioinfo1/projects/bean/MinIon/software/Test_cule                                                                                             brONT/culebrONT_OUTPUT/5percentB1-1/LOGS/ASSEMBLER/CANU/5percentB1-1_CANU.e (check log file(                                                                                             s) for error message)
    shell:

        [ ! -f /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5perc                                                                                             entB1-1/ASSEMBLERS/CANU/ASSEMBLER/CANU-version.txt ] &&  [ ! -d versions ] && mkdir -p versi                                                                                             ons; canu --version > /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPU                                                                                             T/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/CANU-version.txt
        ln -s -f /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5pe                                                                                             rcentB1-1/ASSEMBLERS/CANU/ASSEMBLER/CANU-version.txt /bioinfo1/projects/bean/MinIon/software                                                                                             /Test_culebrONT/culebrONT_OUTPUT/versions/CANU-version.txt
        (canu useGrid=false -p out_canu -d /bioinfo1/projects/bean/MinIon/software/Test_cule                                                                                             brONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/ genomeSize=4.8m -nanopore  /b                                                                                             ioinfo1/projects/bean/MinIon/software/Test_culebrONT/Data-Xoo-sub/fastq/5percentB1-1.fastq.g                                                                                             z;
        ln -s -f /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5pe                                                                                             rcentB1-1/ASSEMBLERS/CANU/ASSEMBLER/out_canu.contigs.fasta /bioinfo1/projects/bean/MinIon/so                                                                                             ftware/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBLERS/CANU/ASSEMBLER/assembly.fasta                                                                                             ) 1>/bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/LOG                                                                                             S/ASSEMBLER/CANU/5percentB1-1_CANU.o 2>/bioinfo1/projects/bean/MinIon/software/Test_culebrON                                                                                             T/culebrONT_OUTPUT/5percentB1-1/LOGS/ASSEMBLER/CANU/5percentB1-1_CANU.e

        (one of the commands exited with non-zero exit code; note that snakemake uses bash s                                                                                             trict mode!)
Logfile /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1                                                                                             /LOGS/ASSEMBLER/CANU/5percentB1-1_CANU.o:

usage:   canu [-version] [-citation] \
              [-haplotype | -correct | -trim | -assemble | -trim-assemble] \
              [-s <assembly-specifications-file>] \
               -p <assembly-prefix> \
               -d <assembly-directory> \
               genomeSize=<number>[g|m|k] \
              [other-options] \
              [-haplotype{NAME} illumina.fastq.gz] \
              [-corrected] \
              [-trimmed] \
              [-pacbio |
               -nanopore |
               -pacbio-hifi] file1 file2 ...

example: canu -d run1 -p godzilla genomeSize=1g -nanopore-raw reads/*.fasta.gz

  To restrict canu to only a specific stage, use:
    -haplotype     - generate haplotype-specific reads
    -correct       - generate corrected reads
    -trim          - generate trimmed reads
    -assemble      - generate an assembly
    -trim-assemble - generate trimmed reads and then assemble them

  The assembly is computed in the -d <assembly-directory>, with output files named
  using the -p <assembly-prefix>.  This directory is created if needed.  It is not
  possible to run multiple assemblies in the same directory.

  The genome size should be your best guess of the haploid genome size of what is being
  assembled.  It is used primarily to estimate coverage in reads, NOT as the desired
  assembly size.  Fractional values are allowed: '4.7m' equals '4700k' equals '4700000'

  Some common options:
    useGrid=string
      - Run under grid control (true), locally (false), or set up for grid control
        but don't submit any jobs (remote)
    rawErrorRate=fraction-error
      - The allowed difference in an overlap between two raw uncorrected reads.  For lower
        quality reads, use a higher number.  The defaults are 0.300 for PacBio reads and
        0.500 for Nanopore reads.
    correctedErrorRate=fraction-error
      - The allowed difference in an overlap between two corrected reads.  Assemblies of
        low coverage or data with biological differences will benefit from a slight increase
        in this.  Defaults are 0.045 for PacBio reads and 0.144 for Nanopore reads.
    gridOptions=string
      - Pass string to the command used to submit jobs to the grid.  Can be used to set
        maximum run time limits.  Should NOT be used to set memory limits; Canu will do
        that for you.
    minReadLength=number
      - Ignore reads shorter than 'number' bases long.  Default: 1000.
    minOverlapLength=number
      - Ignore read-to-read overlaps shorter than 'number' bases long.  Default: 500.
  A full list of options can be printed with '-options'.  All options can be supplied in
  an optional sepc file with the -s option.

  For TrioCanu, haplotypes are specified with the -haplotype{NAME} option, with any
  number of haplotype-specific Illumina read files after.  The {NAME} of each haplotype
  is free text (but only letters and numbers, please).  For example:
    -haplotypeNANNY nanny/*gz
    -haplotypeBILLY billy1.fasta.gz billy2.fasta.gz

  Reads can be either FASTA or FASTQ format, uncompressed, or compressed with gz, bz2 or xz.

  Reads are specified by the technology they were generated with, and any processing perform                                                                                             ed.

  [processing]
    -corrected
    -trimmed

  [technology]
    -pacbio      <files>
    -nanopore    <files>
    -pacbio-hifi <files>

Complete documentation at http://canu.readthedocs.org/en/latest/

ERROR:  Invalid command line option '/bioinfo1/projects/bean/MinIon/software/Test_culebrONT/                                                                                             Data-Xoo-sub/fastq/5percentB1-1.fastq.gz'.  Did you forget quotes around options with spaces                                                                                             ?

Logfile /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1                                                                                             /LOGS/ASSEMBLER/CANU/5percentB1-1_CANU.e:

Removing output files of failed job run_canu since they might be corrupted:
/bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_OUTPUT/5percentB1-1/ASSEMBL                                                                                             ERS/CANU/ASSEMBLER/CANU-version.txt
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: ../../.snakemake/log/2022-03-25T152727.492895.snakemake.log

Thanks in advance

**Comment by serbier** [comment]
I was running the singularity image in a different partition where test files are stored and with --singularity-args "--bind PATH_TO_TEST_FILES" I could resolve the issue. Many thanks!

**Comment by scunnac** [comment]
Related to issue #6. Similarly solved.
